### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by whoooami** [urunimi/NettyAndroid#1]
Did I missing something, I can't find com.hovans.android.service.ServiceUtil.java . The package com.hovans.android is missing in my fork!

**Comment by urunimi** [comment]
Hi.

Sorry for confusing.

Use this project.
https://github.com/urunimi/CodelabLibrary

Thanks.

On Mon, Mar 16, 2015 at 8:53 PM, nothing-whoami notifications@github.com
wrote:

> Did I missing something, I can't find
> com.hovans.android.service.ServiceUtil.java .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/urunimi/NettyAndroid/issues/1.

## 

Best regards,
Hovan PyungWoo Yoo.

**Comment by whoooami** [comment]
@urunimi Thank you! That's very helpful!
